server:
  port: 8080

jwt:
  public.key: classpath:app.pub
  private.key: classpath:app.key

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_ENDPOINT:127.0.0.1:3306}/${DATABASE:a_platform}?serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&characterEncoding=UTF-8
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:root}
  thymeleaf:
    cache: false
  flyway:
    baseline-on-migrate: true
    out-of-order: true
    validate-on-migrate: false
  security:
    oauth2:
      client:
        registration:
          gitee:
            client-id: your-client-id
            client-secret: your-client-secret
            #             ClientAuthenticationMethod
            client-authentication-method: client_secret_basic
            #             AuthorizationGrantType
            authorization-grant-type: authorization_code
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/gitee
            scope: user_info
            client-name: Gitee
        provider:
          gitee:
            authorization-uri: https://gitee.com/oauth/authorize
            token-uri: https://gitee.com/oauth/token
            user-info-uri: https://gitee.com/api/v5/user
            userNameAttribute: name